### ISSUE TITLE
Passing cov to extend_STR_reads

### ISSUE THREAD

**Issue by bergeycm** [aakrosh/BaitSTR#3]
The usage and example given for extend_STR_reads in the README does not include the cov parameter unlike the actual usage. If you do run the program and exclude cov, it does run, provided there are not other options so the example given with the test dataset does actually work. This is because it just checks for the number of arguments [extend_STR_reads.c:1016 (argc < 4)].

**Comment by aakrosh** [comment]
Thanks for catching that. Changed it to check for (argc < 7).
